- name: Gitlab SSO
  hosts: cas-server


  vars_prompt:
    - name: gitlab_access_token
      prompt: Gitlab admin's Access token

    - name: sonarqube_username
      prompt: Sonarqube administrator's username
      private: false
    - name: sonarqube_password
      prompt: Sonarqube administrator's password

    - name: mattermost_username
      prompt: Mattermost administrator's username
      private: false
    - name: mattermost_password
      prompt: Mattermost administrator's password


  tasks:
    - name: Setup SSO in Taiga
      import_tasks:
        file: ./sso/taiga.yml

    - name: Setup SSO in Sonarqube
      import_tasks:
        file: ./sso/sonarqube.yml

    - name: Setup SSO in Mattermost
      import_tasks:
        file: ./sso/mattermost.yml