- name: Create a Gitlab OAuth application
  ansible.builtin.uri:
    url: "{{ schema }}://{{ domain }}{{ gitlab_path }}/api/v4/applications"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_access_token }}"
    body_format: json
    body:
      name: "Mattermost"
      redirect_uri: "{{ schema }}://{{ domain }}{{ mattermost_path }}/login/gitlab/complete\n{{ schema }}://{{ domain }}{{ mattermost_path }}/signup/gitlab/complete"
      scopes: "api"
    status_code: 201
  register: gitlab_oauth


- name: Auth to mmctl
  become: true
  community.docker.docker_container_exec:
    container: cas-mattermost
    command: mmctl auth login {{ schema }}://{{ domain }}{{ mattermost_path }} --name cas-mm-server --username {{ mattermost_username }} --password {{ mattermost_password }}
    chdir: /


- name: Setup Gitlab SSO
  become: true
  block:
    - community.docker.docker_container_exec:
        container: cas-mattermost
        command: mmctl config set GitLabSettings.Enable true
        chdir: /

    - community.docker.docker_container_exec:
        container: cas-mattermost
        command: mmctl config set GitLabSettings.Id {{ gitlab_oauth.json.application_id }}
        chdir: /

    - community.docker.docker_container_exec:
        container: cas-mattermost
        command: mmctl config set GitLabSettings.Secret {{ gitlab_oauth.json.secret }}
        chdir: /

    - community.docker.docker_container_exec:
        container: cas-mattermost
        command: mmctl config set GitLabSettings.AuthEndpoint {{ schema }}://{{ domain }}{{ gitlab_path }}/oauth/authorize
        chdir: /

    - community.docker.docker_container_exec:
        container: cas-mattermost
        command: mmctl config set GitLabSettings.TokenEndpoint {{ schema }}://{{ domain }}{{ gitlab_path }}/oauth/token
        chdir: /

    - community.docker.docker_container_exec:
        container: cas-mattermost
        command: mmctl config set GitLabSettings.UserAPIEndpoint {{ schema }}://{{ domain }}{{ gitlab_path }}/api/v4/user
        chdir: /


- name: Delete credentials from mmctl
  become: true
  community.docker.docker_container_exec:
    container: cas-mattermost
    command: mmctl auth delete cas-mm-server
    chdir: /