- name: Create root directory
  become: true
  file:
    path: "{{ taiga_directory }}"
    state: directory
    mode: '0770'

- name: Create required directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ taiga_directory }}/db-data"
    - "{{ taiga_directory }}/media-data"

- name: Copy nginx configuration
  become: true
  template:
    src: taiga.conf
    dest: "{{ taiga_directory }}/taiga.conf"
    mode: '0770'

- name: Copy docker-compose
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ taiga_directory }}/docker-compose.yml"
    owner: root
    mode: '0700'

- name: Docker compose up
  become: true
  community.docker.docker_compose:
    project_src: "{{ taiga_directory }}"
    remove_orphans: true


- name: Copy backup script
  become: true
  template:
    src: backup.sh.j2
    dest: "{{ taiga_directory }}/backup.sh"
    mode: '0770'

- name: Backup cron
  become: true
  ansible.builtin.cron:
    name: Taiga backup
    weekday: "{{ backup_weekday }}"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    user: root
    job: "{{ taiga_directory }}/backup.sh"